typography_spectrum: 0.20678
color:
  brandColors:
    - '#b1b1bd'
    - '#02000b'
    - '#858793'
    - '#3b99b2'
    - '#0b2864'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: wilsonsaloj
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: wilsonsaloj
purpose: []
