typography_spectrum: 0.1650955572258681
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.7282479610294104
  lightness: 0.2300418931990862
  saturation: 0.848670004401356
  rhythmicContrast: 0.4631281627807766
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9036106313578784
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: wilsonsaloj
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: wilsonsaloj
purpose: []
