name: wilsonsaloj
favicon: null
layout_spectrum: 0.0242
typography_spectrum: 0.20678
title: wilsonsaloj
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1b1bd'
    - '#02000b'
    - '#858793'
    - '#3b99b2'
    - '#0b2864'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
