name: wilsonsaloj
favicon: null
layout_spectrum: 0.9275939783547074
typography_spectrum: 0.43725548684597015
title: wilsonsaloj
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b6b7b2'
    - '#040507'
    - '#525254'
    - '#618263'
    - '#0463a5'
  brandStrength: 0.7032300904393196
  lightness: 0.11474162386730313
  saturation: 0.790433760965243
  rhythmicContrast: 0.3137663574889302
purpose: []
